### ISSUE TITLE
Valid but incorrectly formatted phone numbers no longer auto-correct

### ISSUE THREAD

**Issue by nttaylor** [OpenTechStrategies/streetcrm#187]
In the ajax-populated attendee list of the "change action" form, entering a valid but incorrectly formatted phone number like "555-555-5555" does not get reformatted to "(555) 555-5555" (the preferred formatting) until after the page is refreshed. Before the implementation of the click-to-edit interface this used to happen immediately upon save. It should be that way again.

**Comment by cecilia-donnelly** [comment]
This, and the associated problem mentioned in #200 and #260, continues to be an issue.  It came up again in a meeting on [2017-06-08], so I'm marking it high priority for the next milestone.
