### ISSUE TITLE
Basic search doesn't find institutions

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/streetcrm#244]
I'm not sure why, but the basic search returns actions, participants, and tags -- not institutions.  Obviously it should, so I need to figure out why that is and fix it.

**Comment by xray7224** [comment]
You need to specify the `search_fields` line on the admin, you can see how it works on the Event model here https://github.com/OpenTechStrategies/swoptact/blob/master/swoptact/admin.py#L772
