### ISSUE TITLE
Should we allow participants to skip stages?

### ISSUE THREAD

**Issue by GovInTrenches** [OpenTechStrategies/streetcrm#264]
One of the things I noticed was that as staff I could assign leadership stages without specifying if they reached the previous ones. 

http://swoptact.opentechstrategies.com/swoptact/participant/5/ 

I wasn't sure if this was intentional (not being super familiar with SWOP's process)

**Comment by cecilia-donnelly** [comment]
We didn't specifically discuss it with them, but I think it's the right way to treat this at the moment.  They already have a lot of leaders who are at advanced stages, and I think they'll likely enter them with "primary" or "secondary" right away.  I think they would balk at being forced to enter the earlier stages all in a row just to designate someone as "primary" who has already been working with the group for a long time.

It'll take them a while to enter all their organizers and volunteers, and it probably would be relatively frequent for someone to already be at an advanced leadership stage by the time he or she is entered into the system.
