### ISSUE TITLE
On login screen, upper-right menu pulldown icon does nothing.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/streetcrm#279]
If you go to the front page of https://lisc.streetcrm.com/ right now, if you aren't logged in, you'll be redirected to https://lisc.streetcrm.com/login/?next=/ .  Click on the three-horizontal-bar menu icon in the upper right.  Notice how nothing happens, except that an inexplicable tiny little gray pixel appears down near the lower right of the icon.  I do not think the user will know what to do with the tiny little gray pixel, except possibly take it home and feed it (that's what I did, but then I'm a developer).

I guess if the menu icon offers nothing on that page, we should just remove it.

I tried to find out what happens with the menu icon after one logs in, but with both the `ots-test` and `ots-admin` users (got their passwords from the asset keys file as per usual), when I tried to log in, I just got brought back to the Login page, with this message showing:

> Please enter the correct username and password for your account. Note that both fields are case-sensitive

So, not sure what's going on with that -- maybe it should be a separate issue, unless it's just that our asset keys database is out of date?

**Comment by cecilia-donnelly** [comment]
@kfogel I can remove the icon from the homepage when a user isn't logged in, for sure.

If you search "lisc.streetcrm users" in the asset keys file you'll find a usable login.  The user list for that instance isn't clearly differentiated from those for other instances, which I can update too.
