### ISSUE TITLE
Basic search behaves unexpectedly

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/streetcrm#280]
I see two problems with the current basic search on the `swoptact-safe-deploy` branch (and probably on master as well): 

1. It does not find institutions.
2. It often shows "None" in the results.

These may be related.  A possible third issue (cc: @kfogel) is that the search does not do any suggestion or fuzzy matching.  If I search for "Cecilia Donnely" instead of "Cecilia Donnelly," I won't get any results.  We may be able to address that with training (e.g. search for "C* D*" if you're not sure how to spell a person's name), including more help text in the app itself.

**Comment by cecilia-donnelly** [comment]
Note that wildcards (specifically "*", I haven't observed this with anything else) behave differently with a SQLite backend than with a PostgreSQL backend.  This is shocking to me, but appears to be true.  With SQLite, the search "D*" gets no results from the sample data, where with PostgreSQL it returns three results ("International Women's Day," "Daria Lagos," and "Dante Stallworth").

**Comment by cecilia-donnelly** [comment]
Maybe we should be registering models:

https://github.com/etianen/django-watson/wiki/registering-models
https://github.com/etianen/django-watson/wiki/Searching-models

I know we have some custom search behavior, so this might not be the way to go.  See @xray7224's comment in #244 about finding institutions with search.

**Comment by cecilia-donnelly** [comment]
Re [my earlier comment](https://github.com/OpenTechStrategies/streetcrm/issues/280#issuecomment-276479960) about wildcard escaping, see https://github.com/etianen/django-watson/pull/183.  It looks like someone recently edited Watson's escaping to work with both Postgres and MySQL, but not SQLite.  I think the necessary change would be to add SQLite escaping to `backends.py`.

**Comment by kfogel** [comment]
If you want to do that and contribute it upstream, +1 here.  (I mean, unless you judge it to be a huge effort.)

**Comment by cecilia-donnelly** [comment]
@kfogel I'll look into it.  For my future research, these are probably also relevant: https://github.com/etianen/django-watson/issues/134 and https://github.com/etianen/django-watson/issues/25.

**Comment by cecilia-donnelly** [comment]
Current tasks:

- [ ]  Write a script to convert existing institutions into SearchEntry objects
- [ ]  Reproduce the "None" search results
- [ ]  Then, remove "None" search results

**Comment by cecilia-donnelly** [comment]
After discussing a bit with @kfogel, two more to-do items:

- [ ] Log all searches, so we know what kinds of strings people are actually using
- [ ] Write a well-defined description of how search *should* work (e.g. matching on all substrings), and check that with the users

**Comment by cecilia-donnelly** [comment]
I think we can probably manually log searches using something like the answer [here](http://stackoverflow.com/questions/7905106/adding-a-log-entry-for-an-action-by-a-user-in-a-django-app).  Search queries aren't objects, so it would look more like:

```
        LogEntry.objects.log_action(
            user_id=request.user.id,
            content_type_id=None,
            object_id=None,
            object_repr=search_query,
            action_flag=SEARCH)
```

But I'm not sure whether this will play nicely with our existing `ActivityLog` model.

(Sorry, everyone subscribed to this thread.  I'm trying to keep track of my thinking in some detail.)

**Comment by cecilia-donnelly** [comment]
Added logging for basic searches in 758192f.

**Comment by cecilia-donnelly** [comment]
My understanding of how basic search should work, to be checked with users:

When a user types a string like "donn" into the search bar, they should receive as a result any Participant, Institution, Action, or Tag whose name field includes that string (in any position, not just at the beginning).

Currently, search also matches on other fields (see the search_fields field on each model in `admin.py`).  I'm not sure how useful that is for users.  Our logging data will help us see how often they search on a participant's address or an action's location.

**Comment by cecilia-donnelly** [comment]
Okay, more understanding: I can now reproduce the "None" results, and I understand what happened.  When we cleared the database on the beta site so that our users could start testing with real data, we deleted all the participants, institutions, and events (full list of the tables we cleared:  `"swoptact_leadershipgrowth," "django_admin_log," "swoptact_event_participants," "swoptact_event_tags," "swoptact_event," "swoptact_institution_contacts," "swoptact_institution_tags," "swoptact_participant," "swoptact_institution," "swoptact_tag"`).  However, we didn't clear the `watson_searchentry` table, so all of those forgotten objects still have entries in it!

Now, when one of these matches a search query, it shows up in the results as `None`, because it isn't a real object.  This should, happily, be pretty easy to fix: remove all the entries in the `watson_searchentry` table that don't correspond to a real object (i.e., all the entries before some date).  After that, don't manually delete objects from the database!

Really, there should be some kind of foreign key relationship between objects and their `searchentry` entries, so that we can cascade on delete.

**Comment by cecilia-donnelly** [comment]
Rather than writing a script to add existing Institutions to the `watson_searchentry` table, I can use the admin command `./manage.py buildwatson`.  This probably removes the need to manually remove the search entries that point to deleted objects, too.  I'll do some more testing locally and then run on the testing server.

At worst, I may need to run `truncate watson_searchentry` and then the `buildwatson` command.  Most likely, though, `buildwatson` will handle this on its own.

**Comment by kfogel** [comment]
*nod*  Excellent discovery!

**Comment by cecilia-donnelly** [comment]
Deployed on [2017-02-06].
