### ISSUE TITLE
Grant admin users ability to delete objects

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/streetcrm#290]
Administrative users may occasionally wish to actually delete (instead of archiving) objects.  This is something we would want to limit to admin users only, and would require some UI work to distinguish the "Archive" button from a new "Delete" button.

I think looking at #32 for more information about how we switched from "Delete" to "Archive" is probably the place to start for this one.

**Comment by kfogel** [comment]
Tentatively in 22-March-2017 milestone.  If it turns out this requires a lot of research, it can be dropped from that milestone.
