### ISSUE TITLE
Cosmetic changes to Home page: move "Tags" to bottom, and remove "Site Administration".

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/streetcrm#291]
On the Home page that serves as the default dashboard for logged-in users, we can get rid of the "SIte Administration" title across the top, and the "Tags" item (which is currently listed first even though it's the least frequently used) can be moved to the bottom, in its own section under the "Advanced Search" section.

**Comment by cecilia-donnelly** [comment]
Deployed on [2017-03-10].
