### ISSUE TITLE
Exported CSV file should have unique date+time stamp.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/streetcrm#293]
Right now, export files are just `search-results.csv`.  Someone could accidentally overwrite an existing results file with a new one of the same name.  Instead, how about `streetcrm-search-results-YYYYMMDD-HH:MM:SS.csv`?

**Comment by cecilia-donnelly** [comment]
Even though I set colons between HH, MM, and SS in the code, these are separated by underscores in Firefox and hyphens in Chromium.  Maybe this is because of some caching in my local copy (I was using underscores before).
