### ISSUE TITLE
Access logs and error logs should have datestamped entries.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/streetcrm#296]
In `out.log` and `err.log`, the entries do not have the date and time.  Obviously, they should.

The format of `out.log` is particularly weird, with non-printing chars as entry delimiters, etc.  It does seem that `out.log` has relative timestamps (time since startup), but that's inconvenient when one is trying to match up access entries with some known incident.

**Comment by cecilia-donnelly** [comment]
@kfogel I think this might have been meant to be https://github.com/redcross/smoke-alarm-portal/issues/224?  Logs for this project do have timestamps, and are handled by Apache (see [apache-24.conf](https://github.com/OpenTechStrategies/streetcrm/blob/master/apache-24.conf)).

Our internal logs, meanwhile, are still in progress (see #255 for recent work).

**Comment by kfogel** [comment]
AHA!  *That's* where it went!  Remember when I had lost an issue?  This must be what happened.

**Comment by cecilia-donnelly** [comment]
Yes!  I do remember. :)
