### ISSUE TITLE
Alphabetize attendees by first-last

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/streetcrm#304]
On the sign-in sheet that appears on action change pages, alphabetize attendees.

Certainly whenever a user navigates to the page, all the attendees should be alphabetized.  However, when the user is adding new attendees (usually from a paper sign in sheet), they should *not* reorder themselves right away.  That would (probably) make it hard for the user to keep track of their place on the paper sign-in sheet.

Essentially, the behavior should stay the same except that instead of ordering attendees by their database ID number (which is meaningless to users), order them by name.

**Comment by kfogel** [comment]
+1 to the logic above
