### ISSUE TITLE
Pop out participant info from sign-in sheet

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/streetcrm#308]
When a user is on the sign-in sheet (the action page) and clicks on a Participant's details, a new browser tab is created.  But 99% of the time, this is too heavyweight -- usually you're just confirming that it's who you think it is or looking up a quick fact about the person, and once you've done that you'll want the information to go away again.  A temporary popup of some kind is a better way to do that; the popup can have an option for expanding to its own first-class browser tab.

**Comment by pjsier** [comment]
Are they generally just looking for things like title and address, or would they want everything on the detail page currently like action history?

**Comment by cecilia-donnelly** [comment]
I think they want the pieces above the horizontal line on the participant form, right.  So, not the action history, not the leader stages.  And we'll leave a link there so they can get to the full page if they want/need to.
