### ISSUE TITLE
Pop-up optimization

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/streetcrm#323]
@pjsier, do you think it would possible to close the new participant pop-up when the user clicks outside the pop-up or hits ESC?  I find myself wanting to close it without moving the mouse all the way over to the "X."

**Comment by pjsier** [comment]
@cecilia-donnelly yeah, I don't think that should be too much trouble. This StackOverflow answer seems like a straightforward way of doing it https://stackoverflow.com/a/27759070, so I can add that now
